pipelines:
  default:
    - parallel:
        - step:
            services:
              - php
              - mysql
            name: Test
            script:
              - apt-get update && apt-get install -y unzip
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
              - php -r "file_exists('.env') || copy('.env.example', '.env');"
              - php artisan key:generate
              - chmod -R 777 storage bootstrap/cache
              - php artisan migrate:fresh
              - php artisan db:seed
              - ./vendor/bin/pest test
              - ./vendor/bin/phpstan
            caches:
              - composer

definitions:
  services:
    php:
      image: php:8.2
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'laravel'
        MYSQL_USER: 'sail'
        MYSQL_PASSWORD: 'password'
