image: cgsmith105/php:8.3

clone:
  depth: 1

pipelines:
  branches:
    master:
      - step:
          services:
            - mysql
          name: Test application and Deploy to Production
          script:
            - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
            - export NVM_DIR="$HOME/.nvm"
            - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
            - nvm install 20
            - npm install
            - npm run build
            - export COMPOSER_ALLOW_SUPERUSER=1
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - php -r "file_exists('.env') || copy('.env.example', '.env');"
            - php artisan key:generate
            - chmod -R 777 storage bootstrap/cache
            - php artisan migrate:fresh --seed
            - php artisan serve &
            - composer test
            - ssh-keyscan $SERVER >> ~/.ssh/known_hosts
            - php vendor/bin/dep deploy
          caches:
            - composer
definitions:
  services:
    mysql:
      image: mysql:8.0
      variables:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: 'laravel'
        MYSQL_USER: 'sail'
        MYSQL_PASSWORD: 'password'
